#######################################################################
# Copyright (C)2012, International Business Machines Corporation and
# others. All Rights Reserved.
#######################################################################

all:
	spl-make-toolkit -m -i .
	
clean: cleanspldoc
	spl-make-toolkit -c -i .
	
spldoc:
	spl-make-doc -i .
	
cleanspldoc:
	rm -Rf doc		
	
		
	
	
	
	

